### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by sangujung-eca21a** [eca21a/HelpDesk#20]
org:eca21x
repo:eca21a-00-00-10-sangujung-eca21a

https://github.com/eca21x/eca21a-00-00-10-sangujung-eca21a

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-10-sangujung-eca21a
Processing request above

**Comment by sangujung-eca21a** [comment]
org:eca21x
repo:eca21a-00-00-10-sangujung-eca21a

https://github.com/eca21x/eca21a-00-00-10-sangujung-eca21a

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-10-sangujung-eca21a
Processing request above

**Comment by sangujung-eca21a** [comment]
org:eca21x
repo:eca21a-00-00-10-sangujung-eca21a

https://github.com/eca21x/eca21a-00-00-10-sangujung-eca21a

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-10-sangujung-eca21a
Processing request above

**Comment by sangujung-eca21a** [comment]
org : eca21x
repo : eca21a-00-00-10-sangujung-eca21a
https://github.com/eca21x/eca21a-00-00-10-sangujung-eca21a

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-10-sangujung-eca21a
Processing request above

**Comment by kangwonlee** [comment]
사정상 https://github.com/eca21x/ 와 https://github.com/eca21x/HelpDesk 사용 바랍니다
org 와 repo 사이의 빈 줄 삭제 바랍니다
