### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by 2020114011-cpf21a** [eca21a/HelpDesk#29]
org: eca21x

repo: eca21a-00-00-10-2020114011-cpf21a

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Could not find the repo name in comment

**Comment by kangwonlee** [comment]
@2020114011-cpf21a 
활성화 된 것으로 보입니다
그리고 사정상 eca21x 에서 신청 바랍니다
