### ISSUE TITLE
활성화 바랍니다

### ISSUE THREAD

**Issue by 2017114012-kimjungyeon** [eca21a/HelpDesk#30]
org: eca21x
repo: https://github.com/eca21a/eca21a-nmisp-2017114012-kimjungyeon

https://github.com/eca21x/eca21a-00-00-10-2017114012-kimjungyeon

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Repo https seems out of scope

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Org your_org_here seems out of scope

**Comment by 2017114012-kimjungyeon** [comment]
org : eca21x
repo : eca21a-00-00-10-2017114012-kimjungyeon
https://github.com/eca21x/eca21a-00-00-10-2017114012-kimjungyeon
