### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by KangMinjea-eca21a** [eca21a/HelpDesk#9]
org: eca21x
repo:  eca21a-00-00-10-KangMinjae-eca21a

https://github.com/eca21x/eca21a-00-00-10-KangMinjea-eca21a

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-10-KangMinjae-eca21a
Processing request above

**Comment by kangwonlee** [comment]
사정상 https://github.com/eca21x/ 와 https://github.com/eca21x/HelpDesk 사용 바랍니다
